# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNN2CodePush' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNN2CodePush

  

  platform :ios, '9.0'
  target 'RNN2CodePushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNN2CodePush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNN2CodePush-tvOS

  target 'RNN2CodePush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
